### ISSUE TITLE
Svelte 5 migration

### ISSUE THREAD

**Issue by derevyan** [axzilla/boilerbrew#2]
Amazing job guys, one of the best boilerplate on github so far for svelte.
Learning svelte 5 at the moment, will be amazing to see one day you migrate to svelte 5. 
God luck 💛

**Comment by axzilla** [comment]
Thank you so much for the kind words! 😊 I'm glad you like it. At the moment, I'm focusing on a few other priorities, but who knows? Maybe one day I'll get around to exploring Svelte 5 too. Stay tuned, and happy coding! 💛
